on:
    push:
        paths:
            - '**.sarif'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            security-events: write
            actions: read
            contents: read

        steps:
            - uses: actions/checkout@v3
            - uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: fixtures/arenas.sarif
